### ISSUE TITLE
why is the main.py empty？

### ISSUE THREAD

**Issue by QianyuanLiu** [DreamFly1993/nao_talksystem#1]
Hi，
I am interesting in your work. And i want to reimplement this work.
why is the main.py empty？
could you help me ?
thank you !

**Comment by DreamFly1993** [comment]
Hello,
this is a simple implementation of Q-learning method for conference room
ordering.
It depends on the API of NaoQi robot.

It is the homework of one of my courses, so I set it to Private at the
beginning.
But that's fine, you can use it just for reference and start the system
using talking_sys.py
<https://github.com/DreamFly1993/nao_talksystem/blob/master/talking_sys.py>.


Best wishes,

DreamFly



2018-01-08 11:10 GMT+08:00 liuqy1994 <notifications@github.com>:

**Comment by QianyuanLiu** [comment]
Thank you for your replying ！
我是一个新手，刚接触NAO机器人不久，国内的相关资料很少。
非常感谢能有像您这样的前辈做出的努力来指引我们。
以后有什么问题还要多多请教您！
再次致谢~
